<a href="https://colab.research.google.com/github/Sinrez/PythonProjects/blob/main/k_NN_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Метод $k$-ближайших соседей

Чтение данных

In [ ]:
import pandas as pd
import numpy as np
# train_data = pd.read_csv("Task_data.csv", delimiter=',', index_col='id')
train_data = pd.DataFrame(np.array([
    [22, 86, 0],
    [78, 32, 1],
    [54, 50, 1],
    [68, 80, 0],
    [18, 12, 0],
    [85, 48, 0],
    [78, 10, 0],
    [50, 74, 0],
    [30, 95, 0],
    [91, 12, 0]
]), columns=['X', 'Y', 'Class'])

Вывод всех строк данных

In [ ]:
train_data

X   Y  Class
0  22  86      0
1  78  32      1
2  54  50      1
3  68  80      0
4  18  12      0
5  85  48      0
6  78  10      0
7  50  74      0
8  30  95      0
9  91  12      0

Отбор данных для предикторов, удаление столбца Class

In [ ]:
X = pd.DataFrame(train_data.drop(['Class'], axis=1))
X.head()

X   Y
0  22  86
1  78  32
2  54  50
3  68  80
4  18  12

Отбор столбца Class для отклика

In [ ]:
y = pd.DataFrame(train_data['Class']).values.ravel()
y

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0])

Подключение библиотеки и задание параметров модели:
n_neighbors — число соседей;
p — используемое расстояние. Манхэттенское расстояние — p=1, евклидово расстояние — p=2.
Дополнительные параметры — https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3, p=1)
neigh.fit(X, y)

KNeighborsClassifier(n_neighbors=3, p=1)

Новый объект, который необходимо классифицировать

In [ ]:
NewObject = [30, 30]

Назначенный класс:

In [ ]:
neigh.predict([NewObject])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1])

Вероятности отнесения к классам 0 и 1 соответственно:

In [ ]:
neigh.predict_proba([NewObject])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([[0.33333333, 0.66666667]])

Вывод расстояний до $k$ соседей в порядке удаления (первый массив — расстояния, второй — идентификаторы объектов). <b>Обращаем внимание</b>, что метод возвращает индексы ближайших соседей с нуля, что не соответствует индексации в таблице.

In [ ]:
neigh.kneighbors([NewObject])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


(array([[30., 44., 50.]]), array([[4, 2, 1]]))