<a href="https://colab.research.google.com/github/Sinrez/PythonProjects/blob/main/Lec_2_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Введение в Машинное обучение

## Высшая Школа Цифровой Культуры

## Материалы к лекции 2. Линейная регрессия

### Примеры

In [ ]:
import pandas as pd
import numpy as np

# Загрузим данные
data = {
    'id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'X': [9, 4, 17, 2, 14, 10, 13, 1, 11, 3],
    'Y': [15, 9, 41, 1, 32, 22, 30, 4, 31, 8]
}

df = pd.DataFrame(data)

# Вычислим выборочные средние x и y
mean_x = df['X'].mean()
mean_y = df['Y'].mean()

# Вычислим коэффициенты theta0 и theta1 с использованием метода наименьших квадратов
x = df['X']
y = df['Y']
theta1 = np.sum((x - mean_x) * (y - mean_y)) / np.sum((x - mean_x) ** 2)
theta0 = mean_y - theta1 * mean_x

# Вычислим статистику R**2
y_pred = theta0 + theta1 * x
ss_total = np.sum((y - mean_y) ** 2)
ss_residual = np.sum((y - y_pred) ** 2)
r_squared = 1 - (ss_residual / ss_total)

print("Выборочное среднее x:", mean_x)
print("Выборочное среднее y:", mean_y)
print("Коэффициент theta1:", theta1)
print("Коэффициент theta0:", theta0)
print("R**2:", r_squared)


Выборочное среднее x: 8.4
Выборочное среднее y: 19.3
Коэффициент theta1: 2.410128388017118
Коэффициент theta0: -0.9450784593437902
R**2: 0.9513257196553756


In [ ]:
#чтение данных, так как названия конфет уникальны, используем их в качестве индекса
import pandas as pd
DATA = pd.read_csv("candy-data.csv", delimiter=',', index_col='competitorname')

In [ ]:
DATA.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 100 Grand to Strawberry bon bons
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   chocolate         70 non-null     int64  
 1   fruity            70 non-null     int64  
 2   caramel           70 non-null     int64  
 3   peanutyalmondy    70 non-null     int64  
 4   nougat            70 non-null     int64  
 5   crispedricewafer  70 non-null     int64  
 6   hard              70 non-null     int64  
 7   bar               70 non-null     int64  
 8   pluribus          70 non-null     int64  
 9   sugarpercent      70 non-null     float64
 10  pricepercent      70 non-null     float64
 11  winpercent        70 non-null     float64
 12  Y                 70 non-null     int64  
dtypes: float64(3), int64(10)
memory usage: 9.7+ KB


In [ ]:
#обучение модели будем проводить на данных, за исключением некоторых конфет
# train_data = DATA.drop(['100 Grand','3 Musketeers','One dime','One quarter','Air Heads'])

train_data = DATA.drop(['Caramel Apple Pops', 'Hersheys Kisses'])

In [ ]:
train_data

chocolate  fruity  caramel  peanutyalmondy  nougat  \
competitorname                                                              
100 Grand                      1       0        1               0       0   
3 Musketeers                   1       0        0               0       1   
One dime                       0       0        0               0       0   
One quarter                    0       0        0               0       0   
Air Heads                      0       1        0               0       0   
...                          ...     ...      ...             ...     ...   
Snickers Crisper               1       0        1               1       0   
Sour Patch Kids                0       1        0               0       0   
Sour Patch Tricksters          0       1        0               0       0   
Starburst                      0       1        0               0       0   
Strawberry bon bons            0       1        0               0       0   

                       crispedricewafer  hard  bar  pluribus  sugarpercent  \
competitorname                                                               
100 Grand                             1     0    1         0         0.732   
3 Musketeers                          0     0    1         0         0.604   
One dime                              0     0    0         0         0.011   
One quarter                           0     0    0         0         0.011   
Air Heads                             0     0    0         0         0.906   
...                                 ...   ...  ...       ...           ...   
Snickers Crisper                      1     0    1         0         0.604   
Sour Patch Kids                       0     0    0         1         0.069   
Sour Patch Tricksters                 0     0    0         1         0.069   
Starburst                             0     0    0         1         0.151   
Strawberry bon bons                   0     1    0         1         0.569   

                       pricepercent  winpercent  Y  
competitorname                                      
100 Grand                     0.860   66.971725  1  
3 Musketeers                  0.511   67.602936  1  
One dime                      0.116   32.261086  0  
One quarter                   0.511   46.116505  0  
Air Heads                     0.511   52.341465  1  
...                             ...         ... ..  
Snickers Crisper              0.651   59.529251  1  
Sour Patch Kids               0.116   59.863998  1  
Sour Patch Tricksters         0.116   52.825947  1  
Starburst                     0.220   67.037628  1  
Strawberry bon bons           0.058   34.578991  0  

[68 rows x 13 columns]

In [ ]:
#отбираем данные для предикторов, удаляя два последних столбца, индекс не включается в данные.
X = pd.DataFrame(train_data.drop(['winpercent', 'Y'], axis=1))

In [ ]:
#указываем столбец отклика
y = pd.DataFrame(train_data['winpercent'])

In [ ]:
#подключаем модель линейной регрессии из библиотеки sklearn
from sklearn.linear_model import LinearRegression

In [ ]:
#обучение модели
reg = LinearRegression().fit(X, y)

In [ ]:
#предсказание для конфет введеных вручную
reg.predict([[1, 0, 0, 1, 1, 0, 0, 1, 1, 0.624, 0.438]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[64.69721336]])

In [ ]:
#предсказание для конфет из таблицы

#выбираем строку из таблицы
AirHeads = DATA.loc['Air Heads',:].to_frame().T

#отбираем данные для предикторов и выполняем предсказание с помощью модели
reg.predict(AirHeads.drop(['winpercent', 'Y'], axis=1))

array([[54.48866347]])

In [ ]:
#предсказание для конфет из таблицы

#выбираем строку из таблицы
AirHeads = DATA.loc['Caramel Apple Pops',:].to_frame().T

#отбираем данные для предикторов и выполняем предсказание с помощью модели
reg.predict(AirHeads.drop(['winpercent', 'Y'], axis=1))

array([[53.68280247]])

In [ ]:
#предсказание для конфет из таблицы

#выбираем строку из таблицы
AirHeads = DATA.loc['Hersheys Kisses',:].to_frame().T

#отбираем данные для предикторов и выполняем предсказание с помощью модели
reg.predict(AirHeads.drop(['winpercent', 'Y'], axis=1))

array([[58.8607841]])

Значение коэффициента $\theta_0$:

In [ ]:
reg.intercept_

array([38.01814174])

Значение коэффициентов $\theta_1, \ldots, \theta_p$:

In [ ]:
reg.coef_

array([[25.43606016, 11.35180477,  0.74567182,  7.8106962 ,  2.28534939,
         9.47304367, -8.52752816, -6.42882564, -5.09991795, 11.21941295,
        -9.8748955 ]])