<a href="https://colab.research.google.com/github/Sinrez/PythonProjects/blob/main/Numpy1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---

# Введение в NumPy


In [1]:
import numpy as np

---

### 3.3 | Индексация, срезы и маски

---

Обращаться к элементам одномерного массива и брать срезы от него можно так:

In [2]:
arr = np.arange(4, 8)
arr, arr[1] # Взятие первого по индексу элемента

(array([4, 5, 6, 7]), 5)

In [3]:
arr[0:2] # Срез от 0 до 2 индекса

array([4, 5])

In [4]:
arr[1:] # Срез от первого индекса и до конца

array([5, 6, 7])

In [5]:
arr[-2:] # Сраз со второго с конца индекса и до конца

array([6, 7])

In [6]:
arr[::-1]

array([7, 6, 5, 4])

---

Использовать индексы и срезы в многомерных массивах можно так:

In [7]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
arr[1, 1]

4

In [9]:
arr[:, 0]

array([1, 3, 5])

In [10]:
arr[-2:, :1]

array([[3],
       [5]])

---

Логические маски можно получать следующим образом:

In [11]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
arr > 3

array([[False, False],
       [False,  True],
       [ True,  True]])

---

Маски можно накладывать на реальные данные:

In [13]:
mask = arr > 3
arr[mask]

array([4, 5, 6])

In [14]:
~mask

array([[ True,  True],
       [ True, False],
       [False, False]])

In [15]:
arr[~mask]

array([1, 2, 3])

---

Поддерживаются также логические операции <<или>> или <<и>>:

In [16]:
mask = ((arr > 0) & (arr % 2 == 0)) | (arr == 5) | (arr == 3)
arr[mask]

array([2, 3, 4, 5, 6])

---

Выделенным ячейкам можно присваивать разные значения:

In [17]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
arr[0, 1] = 10 # Присваиваем конкретной ячейке значение 10
arr

array([[ 1, 10],
       [ 3,  4],
       [ 5,  6]])

In [19]:
arr[1, :] = 0 # Срез ячеек первой строки и всех колонок
arr

array([[ 1, 10],
       [ 0,  0],
       [ 5,  6]])

In [20]:
arr[arr % 2 == 0] = 75 # Все ячейки с нечетными значениями
arr

array([[ 1, 75],
       [75, 75],
       [ 5, 75]])

---

Можно получить индексы всех элементов, удовлетворяющих маске:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.where(arr <  6)

(array([0, 2]), array([0, 0]))

---

Существуют функции $\mathsf{np.hsplit}$ и $\mathsf{np.vsplit}$, разделяющие данные вдоль строк и столбцов:

In [22]:
arr = np.arange(1, 21).reshape((2, -1))
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [30]:
import numpy as np
def new_arr(m, n):
  return np.arange(m,n+1).reshape(3,3)

# def new_arr(m, n):
#     if m > n: # если min > max, меняем местами
#         min1 = m
#         m = n
#         n = min1
#     return np.linspace(m, n, num =  9).reshape(3,3)

new_arr(51,59)

array([[51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [ ]:
np.hsplit(arr, 5)

[array([[ 1,  2],
        [11, 12]]),
 array([[ 3,  4],
        [13, 14]]),
 array([[ 5,  6],
        [15, 16]]),
 array([[ 7,  8],
        [17, 18]]),
 array([[ 9, 10],
        [19, 20]])]

---

Также есть функция $\mathsf{np.copy}$:

In [ ]:
arr = np.arange(6).reshape((2, -1))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr_copy = arr.copy()
arr_copy

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr_copy[arr_copy % 2 == 0] = 10
arr_copy

array([[10,  1, 10],
       [ 3, 10,  5]])

In [ ]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

---