<a href="https://colab.research.google.com/github/Sinrez/PythonProjects/blob/main/py_ing_hw5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random
import numpy as np

def matrix(rows, cols):
  seed = random.randint(1, 2*(rows+cols))
  matrix_a = np.random.randint(1, seed, size=(rows, cols))
  matrix_b = np.random.randint(1, seed, size=(rows, cols))

  matrix_sum = matrix_a + matrix_b

  print("\nМатрица A:")
  print(matrix_a)

  print("\nМатрица B:")
  print(matrix_b)

  print("\nСумма матриц:")
  print(matrix_sum)

if __name__ == "__main__":
  try:
    m = int(input('Введите количество строк: '))
    n = int(input('Введите количество столбцов: '))
    matrix(m, n)
  except ValueError as ve:
      print(f'Должны быть введены только числа: {ve}!')
  except Exception as ex:
      print(f'Произошла ошибка: {ex}')

Введите количество строк: 3
Введите количество столбцов: 4

Матрица A:
[[3 4 5 7]
 [4 2 7 8]
 [5 3 4 6]]

Матрица B:
[[6 2 5 9]
 [3 5 6 1]
 [5 6 6 1]]

Сумма матриц:
[[ 9  6 10 16]
 [ 7  7 13  9]
 [10  9 10  7]]
