<a href="https://colab.research.google.com/github/Sinrez/PythonProjects/blob/main/stepic_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#создаем список на 1кк элементов
lst = list(range(1_000_000))

In [3]:
#создаем аналогичный массив с помощью библиотеки numpy
arr = np.arange(1_000_000)

In [4]:
#возведем каждый элемент в квадрат 10 раз и подсчитаем время выполнения данной операции, командой %time
%time for _ in range(10): lst2 = [x**2 for x in lst]
#результат: 3.65с

CPU times: user 3.48 s, sys: 166 ms, total: 3.65 s
Wall time: 3.7 s


In [5]:
#возведем каждый элемент в квадрат 10 раз с помощью numpy, командой %time
%time for _ in range(10): arr2 = arr ** 2
#результат: 20 мс. Выполнение в сотни раз быстрее

CPU times: user 14.3 ms, sys: 3.03 ms, total: 17.3 ms
Wall time: 20.8 ms


In [6]:
#Создание обычного массива
arr1 = np.array([1,2,3,4.5])
arr1

array([1. , 2. , 3. , 4.5])

In [3]:
import numpy as np

def solution():
    arr = np.zeros((2,5))
    return arr
solution()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
#Step_2.2.5 - Создайте массив заполненный единицами, 
#у которого 5 строк и 8 столбцов (5 вложенных массивов длинной 8)
import numpy as np

def solution():
    arr = np.ones((5,8))
    return arr
solution()

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
# Создайте одномерный numpy массив со значениями 0, 1, 2, .... 99 (диапазон значений от 0 до 99)
import numpy as np

def solution():
    arr = np.arange(0,100)
    return arr
solution()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
#Step_2.2.5 - Создайте двумерный массив размером 5 х 2, который полностью будет заполнен значением 'G' 
import numpy as np

def solution():
    arr = np.full((5, 2), 'G')
    return arr

In [ ]:
import numpy as np

def solution(lst):
    arr = np.array(lst, dtype=np.float64)
    return arr